### ISSUE TITLE
Convert HWP to pdf in linux

### ISSUE THREAD

**Issue by ilovebioz** [ebandal/H2Orestart#11]
Hi,

I am trying to install the H2Orestart extension to libreoffice in Linux to convert the HWP to pdf. 
Can you help to guide how to install and how to use it?

Thank you

**Comment by OctopusET** [comment]
Could you give us information of your linux system?

If you are using Arch Based distro, you can use my [AUR](https://aur.archlinux.org/packages/libreoffice-extension-h2orestart). You can also find this link on the README.

If you are not using Arch based distro or don't want to install it as system package. You can just download .oxt file on Github release or the libreoffice extension page.

On LibreOffice extension page, it could have some older version. Because it's not uploaded by this project's maintainer.

And if you can install it by opening .oxt file on the your favorite file manager. If you are using CLI only or you don't have file manager, I think you can find out the way yourself.

More information on LibreOffice extension installation: https://wiki.documentfoundation.org/Documentation/HowTo/install_extension

**Comment by OctopusET** [comment]
And after installing it, you can convert hwp/hwpx files like other formats. AFAIK it's converted odt format. So no extra work is needed.

**Comment by ilovebioz** [comment]
We are using rocky Linux 9. Do you mean just copy the oxt file to override the previous one or copy it to somewhere in libreoffice install folder?

**Comment by ilovebioz** [comment]
we are using the linux server, UI  is unavailable.

**Comment by OctopusET** [comment]
Then the manual installation would be solution.
Just unzip and copy to the extension directory in the libreoffice.
You can use these scripts as hint.

- https://github.com/freedomofpress/dangerzone/blob/91189e3fb33a66dbbba0e0a7c65040826f84280b/Dockerfile#L42
- https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libreoffice-extension-h2orestart#n20
- https://wiki.documentfoundation.org/Documentation/HowTo/install_extension#Linux_bash_unzip_example

Or this one
- https://ask.libreoffice.org/t/how-to-add-extensions-to-libreoffice-my-system-is-linux-centos/35149

**Comment by ebandal** [comment]
@ilovebioz 
Here is short guide for Ubuntu linux command line. I'm not sure if these commands work for rocky linux. but I think you can figure out.
1. install korean fonts
   $ sudo apt install -y fonts-nanum*
2. install libreoffice packages
   $ sudo apt install -y libreoffice-core libreoffice-writer libreoffice-java-common
3. download H2Orestart.oxt and place to your linux server
4. install it  (unopkg command will be available after you install libreoffice-core or libreoffice-java-common )
  $ sudo unopkg add --shared H2Orestart.oxt
5. convert hwpx file to PDF 
  $ soffice.exe --headless --infilter="Hwp2002_File" --convert-to pdf:writer_pdf_Export  your_hancom_file

**Comment by ilovebioz** [comment]
Hi, I tested your suggestion on Ubuntu and it works. For other Linux distribute required a lot of installation.

**Comment by ebandal** [comment]
Guide provided. No further request.
Closing issue.
